Enables new ePoxy extension bmc-store-password.
m-lab/epoxy pull request #95
Opened 2020-10-27 21:30 UTC by nkinkade

This PR enables a new ePoxy extension named bmc-store-password. It also corrects the FQDN of the `allocate_k8s_token` extension. It was using an old URL that probably only happened to work by chance... a DNS entry was left in place in the zone file that was never removed.

This PR also updates the `epoxy_admin` utility to enable the bmc-store-password extension in GCD by default.

2020-10-27 21:44 UTC, stephen-soltesz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy/95#-:-MKg09uzDYU2Ye2FfVrQ:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)



<!-- Sent from Reviewable.io -->

2020-10-27 22:09 UTC, stephen-soltesz requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy/95)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[cmd/epoxy_admin/command/create.go, line 124 at r1](https://reviewable.io/reviews/m-lab/epoxy/95#-MKg5vaX32-hZFybElLK:-MKg5vaX32-hZFybElLL:b8odfr8) ([raw file](https://github.com/m-lab/epoxy/blob/a75629deebe1214bb294c3dd9e8792cd27707b59/cmd/epoxy_admin/command/create.go#L124)):*
> ```Go
> 	createCmd.Flags().StringVar(&cfTokenExtension, "extension", "allocate_k8s_token",
> 		"Generates k8s join tokens for booting nodes.")
> 	createCmd.Flags().StringVar(&cfBMCExtension, "extension", "bmc_store_password",
> ```

Please add corresponding options to `update` also.


<!-- Sent from Reviewable.io -->

2020-10-27 22:10 UTC, stephen-soltesz reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy/95)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[cmd/epoxy_admin/command/create.go, line 124 at r1](https://reviewable.io/reviews/m-lab/epoxy/95#-MKg5vaX32-hZFybElLK:-MKg65Fx8khopSjZz3Yx:b-lydf63) ([raw file](https://github.com/m-lab/epoxy/blob/a75629deebe1214bb294c3dd9e8792cd27707b59/cmd/epoxy_admin/command/create.go#L124)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add corresponding options to `update` also.
</blockquote></details>

You'll probably be using `update` to fix existing host entities to include the new extension.


<!-- Sent from Reviewable.io -->

2020-10-28 20:24 UTC, nkinkade reviewed
This PR has ended up being a bit more than earlier expected, since epoxy_admin was originally created to only support a single ePoxy extension. This PR now includes changes to easily add new extensions.

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy/95#-:-MKksKquBMjWen3JzLq1:b-qx9bbd)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[cmd/epoxy_admin/command/create.go, line 124 at r1](https://reviewable.io/reviews/m-lab/epoxy/95#-MKg5vaX32-hZFybElLK:-MKksGlD5klTyap5LUdV:b-896fix) ([raw file](https://github.com/m-lab/epoxy/blob/a75629deebe1214bb294c3dd9e8792cd27707b59/cmd/epoxy_admin/command/create.go#L124)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

You'll probably be using `update` to fix existing host entities to include the new extension.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 20:39 UTC, stephen-soltesz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> - thank you!

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy/95#-:-MKkvtJr36qZOuSnbAsp:b-4ev2sm)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2020-10-28 20:50 UTC, merged